/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.util.Date;
import java.util.List;
import model.Project;
import model.Task;

public class App {

    public static void main(String[] args) {

//        Project project = new Project();
//        ProjectController projectController = new ProjectController();
          
//        Create
//        project.setName("Projeto A");
//        project.setDescription("Descrição A");
//        projectController.save(project);
      
//        Update
//        project.setId(1);
//        project.setName("Novo nome para o Projeto A");
//        project.setDescription("Nova descrição para o Projeto A");
//        projectController.update(project);
        
//        Read
//        List<Project> projects = projectController.getAll();
//        System.out.println("Total de projetos = " + projects.size());

//        Delete
//        projectController.removeById(1);


//        Task task = new Task();
//        TaskController taskController = new TaskController();
          
//        Create
//        task.setIdProject(2);
//        task.setName("Tarefa para Projeto A");
//        task.setDescription("Descrição da tarefa para Projeto A");
//        task.setNotes("Notas A");
//        task.setIsCompleted(true);
//        task.setDeadline(new Date());
//        taskController.save(task);
      
//        Update
//        task.setId(1);
//        task.setIdProject(2);
//        task.setName("Novo nome para a tarefa do Projeto A");
//        task.setDeadline(new Date());
//        taskController.update(task);
        
//        Read
//        List<Task> tasks = taskController.getAll(2);
//        System.out.println("Total de tarefas do projeto = " + tasks.size());

//        Delete
//        taskController.removeById(1);
        
    }
    
}
